# Generated by Django 4.0.5 on 2022-06-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210729_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectstaught', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='Subjectstaught',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='Subjectstaught',
            field=models.ManyToManyField(to='directory.subjectsmodel'),
        ),
    ]
